-- INNOVAITE_CLAIMS definition

-- Drop table

-- DROP TABLE INNOVAITE_CLAIMS;

CREATE TABLE INNOVAITE_CLAIMS (
	ID bigint IDENTITY(1,1) NOT NULL,
	CLAIM_NUMBER nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	POLICY_NUMBER nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CUSTOMER_NAME nvarchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SENDER_EMAIL nvarchar(120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PHONE nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CLAIM_AMOUNT numeric(20,10) NULL,
	STATUS nvarchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'PENDING' NOT NULL,
	CREATED_DATE datetime2 DEFAULT sysdatetime() NOT NULL,
	UPDATE_DATE datetime2 DEFAULT sysdatetime() NOT NULL,
	PROCESSED nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REQUEST nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RESPONSE nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SUCCESS bit DEFAULT 0 NOT NULL,
	EMAIL_CONTENT nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EVENT_DESC nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EVENT_DATE datetime2 DEFAULT sysdatetime() NOT NULL,
	CONSTRAINT PK__INNOVAIT__3214EC270F5C10FA PRIMARY KEY (ID)
);
ALTER TABLE BLTC_DEV.dbo.INNOVAITE_CLAIMS WITH NOCHECK ADD CONSTRAINT CK__INNOVAITE__CLAIM__03DEE8D9 CHECK (([CLAIM_AMOUNT]>=(0)));